### ISSUE TITLE
Please add readme.

### ISSUE THREAD

**Issue by damianprzygodzki** [brickgale/simple-react-checkout#1]
The readme with example would be great to understand what is that snippet about.

**Comment by brickgale** [comment]
Updated readme https://github.com/brickgale/simple-react-checkout/commit/8dde312f95f0226a0d54d1de52f4c1d400b6bd74. Right now, just set up the minimum requirements for this simple build. Still having problems with passing request cookies(the goal), tried request, axios, and etc.
